/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2016-03-03 03:01:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>BestDeal</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body BGCOLOR=\"#FFF5EE\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 ALIGN=\"CENTER\">BEST DEAL Inc.</h1>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<h2 ALIGN=\"CENTER\">Checkout</h2>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<p ALIGN=\\\"LEFT\\\">\r\n");
      out.write("\t\t<a href=ModelList.jsp>&nbsp;Home&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a> <a\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=ShoppingCart.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;View\r\n");
      out.write("\t\t\tShopping Cart&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a> \r\n");
      out.write("\t\t<a href=Checkout.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Checkout</a>\r\n");
      out.write("\t</p>\r\n");
      out.write(" \r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("Please fill out the information below:\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<form action=\"Confirmationpage.jsp\" method=\"POST\">\r\n");
      out.write("  First name:\r\n");
      out.write("  <input type=\"text\" name=\"firstName\"><br>\r\n");
      out.write("  Last name:\r\n");
      out.write("  <input type=\"text\" name=\"lastName\"><br>\r\n");
      out.write("  E-mail address:\r\n");
      out.write("  <input type=\"text\" name=\"email\"><br>\r\n");
      out.write("    Street adress:\r\n");
      out.write("  <input type=\"text\" name=\"address\"><br>\r\n");
      out.write("    City:\r\n");
      out.write("  <input type=\"text\" name=\"city\"><br>\r\n");
      out.write("    State:\r\n");
      out.write("  <input type=\"text\" name=\"state\"><br>  \r\n");
      out.write("   Zip code:\r\n");
      out.write("  <input type=\"text\" name=\"zipcode\"><br>\r\n");
      out.write("  Credit Card Number:\r\n");
      out.write("  <input type=\"text\" name=\"creditcardnumber\"><br>\r\n");
      out.write("  <br>\r\n");
      out.write("    <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</BODY></HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
