/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2016-03-12 19:10:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import beans.*;
import controller.CustomerCatalogBean;
import servlet.CustomerController;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<center><img src=\"telecom.png\" alt=\"Hercom Telecom\" width=\"128\" height=\"128\"></center>\r\n");
      out.write("    <title>WideCast Cable</title> \r\n");
      out.write("\t\t <link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheet.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"topright\">\r\n");
      out.write("<a href=\"Main.jsp\">Home&nbsp;</a>\r\n");
      out.write("<a href=\"About.jsp\">About Us&nbsp;</a>\r\n");
      out.write("<a href=\"Contact.jsp\">Contact Us&nbsp;</a>\r\n");
      out.write("<a href=\"http://www.tvguide.com/\">TV Guide</a>\r\n");
      out.write("</nav>\t\t\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<H1 ALIGN=\"CENTER\">WideCast Cable</H1>\r\n");
      out.write("<H3 ALIGN=\"CENTER\"><i>We provide Entertainment for more</i></H3>\r\n");
      out.write("\t\t");
      servlet.CustomerController servletBean = null;
      synchronized (session) {
        servletBean = (servlet.CustomerController) _jspx_page_context.getAttribute("servletBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (servletBean == null){
          servletBean = new servlet.CustomerController();
          _jspx_page_context.setAttribute("servletBean", servletBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<H3 ALIGN=\"CENTER\">Welcome!</H3>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<TABLE WIDTH=\"50%\" border=\"1\" cellspacing=\"3\" cellpadding=\"3\" align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      controller.CustomerCatalogBean customerBean = null;
      synchronized (session) {
        customerBean = (controller.CustomerCatalogBean) _jspx_page_context.getAttribute("customerBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (customerBean == null){
          customerBean = new controller.CustomerCatalogBean();
          _jspx_page_context.setAttribute("customerBean", customerBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<i>Customer Login</i>\r\n");
      out.write("<form name=\"customerform\" method=\"POST\" action=\"servlet/CustomerController?action=getaccount&position=customer\">\r\n");
      out.write("  Username:\r\n");
      out.write("  <input type=\"text\" name=\"userID\"><br>\r\n");
      out.write("  Password:\r\n");
      out.write("  <input type=\"text\" name=\"password\"><br>\r\n");
      out.write("  <br>\r\n");
      out.write("    <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<i>Manager Login</i>\r\n");
      out.write("<br>\r\n");
      out.write("<form name=\"managerform\" method=\"POST\" action=\"servlet/CustomerController?action=getaccount&position=manager\">\r\n");
      out.write("  Username:\r\n");
      out.write("  <input type=\"text\" name=\"userID\"><br>\r\n");
      out.write("  Password:\r\n");
      out.write("  <input type=\"text\" name=\"password\"><br>\r\n");
      out.write("  <br>\r\n");
      out.write("    <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<i>Account Specialist Login</i>\r\n");
      out.write("<br>\r\n");
      out.write("<form name=\"accountform\" method=\"POST\" action=\"servlet/CustomerController?action=getaccount&position=account\">\r\n");
      out.write("  Username:\r\n");
      out.write("  <input type=\"text\" name=\"userID\"><br>\r\n");
      out.write(" Password:\r\n");
      out.write("  <input type=\"text\" name=\"password\"><br>\r\n");
      out.write("  <br>\r\n");
      out.write("    <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<i>Technical Support Login</i>\r\n");
      out.write("<br>\r\n");
      out.write("<form name=\"accountform\" method=\"POST\" action=\"servlet/CustomerController?action=getaccount&position=technical\">\r\n");
      out.write("  Username:\r\n");
      out.write("  <input type=\"text\" name=\"userID\"><br>\r\n");
      out.write(" Password:\r\n");
      out.write("  <input type=\"text\" name=\"password\"><br>\r\n");
      out.write("  <br>\r\n");
      out.write("    <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
