/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2016-03-03 19:14:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import servlet.CartController;
import beans.*;

public final class ModelList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>BestDeal</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body BGCOLOR=\"#FFF5EE\">\r\n");
      out.write("\r\n");
      out.write("\t<h1 ALIGN=\"CENTER\">BEST DEAL Inc.</h1>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<h2 ALIGN=\"CENTER\">Electronics</h2>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<p ALIGN=\\\"LEFT\\\">\r\n");
      out.write("\t\t<a href=ModelList.jsp>&nbsp;Home&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a>\r\n");
      out.write("\t\t<a href=ShoppingCart.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;View Shopping Cart&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a> \r\n");
      out.write("\t\t<a href=Checkout.html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Checkout</a>\r\n");
      out.write("\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      servlet.CartController servletBean = null;
      synchronized (session) {
        servletBean = (servlet.CartController) _jspx_page_context.getAttribute("servletBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (servletBean == null){
          servletBean = new servlet.CartController();
          _jspx_page_context.setAttribute("servletBean", servletBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

		servletBean.readFile();
	
      out.write("\r\n");
      out.write("\t<table width=\"75%\" border=\"1\">\r\n");
      out.write("\r\n");
      out.write("\t\t");

			for (int i = 0; i < 18; i++) {
				String _id = servletBean.getResult().get(i).getItemID();
				String _sDesc = servletBean.getResult().get(i).getShortDescription();
				double _cost = servletBean.getResult().get(i).getCost();
				int _quant = servletBean.getResult().get(i).getQuantity();
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("<form name=\"modelDetail1\" method=\"POST\" action=\"servlet/CartController\">\r\n");
      out.write("\t\t\t\t\t<font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\"><strong>Model:</strong>");
      out.print(_id);
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t<input type='hidden' name='itemID' value= \"");
      out.print(_id);
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t<font face=\"Verdana, Arial, Helvetica, sans-serif\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\"><strong>Description:</strong> ");
      out.print(_sDesc);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</font><input type=\"hidden\" name=\"description\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Tech-Freaks imaginary model 1.\">\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\"><strong>Quantity:\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" size=\"2\" value=\"1\" name=\"quantity\"></strong></font>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<font size=\"2\"><strong>Price</strong>: ");
      out.print(_cost);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"price\" value=");
      out.print(_cost);
      out.write("></font>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("\t\t\t\t\t<input type='hidden' name='itemIndex' value= \"");
      out.print(i);
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"shortDescription\" value= \"");
      out.print(_sDesc);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"quantity\" value= \"");
      out.print(_quant);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"cost\" value= \"");
      out.print(_cost);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"addToCart\" value=\"Add To Cart\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t");

				_id = servletBean.getResult().get(++i).getItemID();
				_sDesc = servletBean.getResult().get(i).getShortDescription();
				_cost = servletBean.getResult().get(i).getCost();
			
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("<form name=\"modelDetail2\" method=\"POST\" action=\"servlet/CartController\">\r\n");
      out.write("\t\t\t\t\t<font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\"><strong>Model</strong>:");
      out.print(_id);
      out.write(" </font>\r\n");
      out.write("\t\t\t\t\t\t<input type='hidden' name='itemID' value= \"");
      out.print(_id);
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t<font face=\"Verdana, Arial, Helvetica, sans-serif\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"2\"><strong>Description</strong>: ");
      out.print(_sDesc);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t2. </font><input type=\"hidden\" name=\"description\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Tech-Freaks imaginary model 2.\">\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"2\"><strong>Quantity</strong>: <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" size=\"2\" value=\"1\" name=\"quantity\"></font>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"2\"><strong>Price</strong>: ");
      out.print(_cost);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"price\" value=");
      out.print(_cost);
      out.write("></font>\r\n");
      out.write("\t\t\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"add\"> \r\n");
      out.write("\t\t\t\t\t\t<input type='hidden' name='itemIndex' value= \"");
      out.print(i);
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"shortDescription\" value= \"");
      out.print(_sDesc);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"quantity\" value= \"");
      out.print(_quant);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"cost\" value= \"");
      out.print(_cost);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" name=\"addToCart\" value=\"Add To Cart\">\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
