/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2016-02-25 02:05:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SerializeCatalog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("import java.io.*;\r\n");
      out.write("\r\n");
      out.write("public class SerializeCatalog\r\n");
      out.write("{\r\n");
      out.write("   public static void main(String [] args)\r\n");
      out.write("   {\r\n");
      out.write("      CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"DroidMAXX\";\r\n");
      out.write("      items.shortDescription = \"Droid MAXX, US version (Gold) - by Motorola\";\r\n");
      out.write("      items.longDescription = \"Take your phone to the Maxx! It comes with charger and a headset. Made in China.\";\r\n");
      out.write("      items.cost = 239.95;\r\n");
      out.write("      \r\n");
      out.write("\t  CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"MotoX\";\r\n");
      out.write("      items.shortDescription = \"Moto X, 2016 version (Black) - by Motorola\";\r\n");
      out.write("      items.longDescription = \"There is no phone like it! It comes with charger and bluetooth headset. Made in China.\";\r\n");
      out.write("      items.cost = 149.99;\r\n");
      out.write("\t  \r\n");
      out.write("\t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"iPhone5S\";\r\n");
      out.write("      items.shortDescription = \"iPhone 5S Designed in California (Rose Gold) - by Apple\";\r\n");
      out.write("      items.longDescription =\"\"Be like everyone else! It comes with charger and a wired headset. Made in China.\";\r\n");
      out.write("      items.cost = 299.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"iPhone5c\";\r\n");
      out.write("      items.shortDescription = \"iPhone 5C Designed in California (Blue) - by Apple\";\r\n");
      out.write("      items.longDescription = \"Everyone has one! It comes with charger and a wired headset. Made in China.\";\r\n");
      out.write("      items.cost = 299.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Galaxy S3\";\r\n");
      out.write("      items.shortDescription = \"Galaxy S3 Ver 2.0 (White) by Samsung\";\r\n");
      out.write("      items.longDescription = \"It's not an iPhone! It comes with charger and 8 GB SD card. Made in Korea.\";\r\n");
      out.write("      items.cost = 159.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Galaxy S4\";\r\n");
      out.write("      items.shortDescription = \"Galaxy S4 US version (Platinum) by Samsung\";\r\n");
      out.write("      items.longDescription = \"Just like the S3, but better! It comes with charger and 16 GB SD card. Made in Korea.\";\r\n");
      out.write("      items.cost = 249.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = Kindle;\r\n");
      out.write("      items.shortDescription = \"Kindle 2.4 Version (Black) by Amazon\";\r\n");
      out.write("      items.longDescription = \"Live in the future, now. It comes with charger and a free ebook. Made in China.\";\r\n");
      out.write("      items.cost = 99.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Nexus\";\r\n");
      out.write("      items.shortDescription = \"Nexus, US version (Platinum) by Samsung\",;\r\n");
      out.write("      items.longDescription = \"Just like the S3, but bigger. It comes with charger and 32 GB SD card. Made in Korea.\";\r\n");
      out.write("      items.cost = 199.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Surface\";\r\n");
      out.write("      items.shortDescription = \"Surface, Windows 10 (Blue) by Microsoft\";\r\n");
      out.write("      items.longDescription = \"Now Windows 10 is portable. It comes with charger and portable keyboard. Made in Vietnam.\";\r\n");
      out.write("      items.cost = 249.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Galaxy\";\r\n");
      out.write("      items.shortDescription = \"Galaxy, US version (Gold) by Samsung\";\r\n");
      out.write("      items.longDescription = \"Just like the S3, but better! It comes with charger and 64 GB internal memory. Made in Korea.\";\r\n");
      out.write("      items.cost = 249.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"iPad\";\r\n");
      out.write("      items.shortDescription = \"iPad, iPad Air(Gold rose) by Apple\";\r\n");
      out.write("      items.longDescription = \"The most popular iPad yet. It comes with charger and headphones. Made in China.\";\r\n");
      out.write("      items.cost = 299.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"MacBook\";\r\n");
      out.write("      items.shortDescription = \"MacBook Brand new (White) by Apple\";\r\n");
      out.write("      items.longDescription = \"Virus free and ready to go! It comes with wall charger and wired mouse.Made in China.\";\r\n");
      out.write("      items.cost = 999.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Asus\";\r\n");
      out.write("      items.shortDescription = \"Asus Windows 10 (Black) by Asus Inc.\";\r\n");
      out.write("      items.longDescription = \"Best warranty in the market. It comes with wall charger and ASUS laptop stickers. Made in Taiwan.\";\r\n");
      out.write("      items.cost = 599.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Sony\";\r\n");
      out.write("      items.shortDescription = \"Sony VAIO Fit (White) by Sony\";\r\n");
      out.write("      items.longDescription = \"Fancy and pricey! It comes with a wall charger and 512 GB SSD. Made in China.\";\r\n");
      out.write("      items.cost = 999.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Lenovo\";\r\n");
      out.write("      items.shortDescription = \"Lenovo, Lenovo X240 (Black) by Lenovo\";\r\n");
      out.write("      items.longDescription = \"The most popular laptop in the market. It comes with a wall charger and a webcam. Made in China.\";\r\n");
      out.write("      items.cost = 599.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Panasonic\";\r\n");
      out.write("      items.shortDescription = \"Panasonic, Panorama Slim (52in) by Panasonic\";\r\n");
      out.write("      items.longDescription = \"1080p definition. It comes with a wall charger and tv mount. Made in Japan.\";\r\n");
      out.write("      items.cost = 799.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"Samsung\";\r\n");
      out.write("      items.shortDescription = \"Samsung Curved (55in) by Samsung\";\r\n");
      out.write("      items.longDescription = \"High definition for less. It comes with a wall mount and Netflix for a year. Made in China.\";\r\n");
      out.write("      items.cost = 999.95;\r\n");
      out.write("\t  \r\n");
      out.write("\t  \t    CatalogItem items = new CatalogItem();\r\n");
      out.write("      items.itemID = \"SonyTV\";\r\n");
      out.write("      items.shortDescription = \"Sony Bravia (70in) by Sony\";\r\n");
      out.write("      items.longDescription = \"4K TV. It comes with a blue-ray player and 3D glasses.Made in China.\";\r\n");
      out.write("      items.cost = 1999.95;\r\n");
      out.write("\r\n");
      out.write("      try\r\n");
      out.write("      {\r\n");
      out.write("         FileOutputStream fileOut =\r\n");
      out.write("         new FileOutputStream(\"/tmp/items.ser\");\r\n");
      out.write("         ObjectOutputStream out = new ObjectOutputStream(fileOut);\r\n");
      out.write("         out.writeObject(items);\r\n");
      out.write("         out.close();\r\n");
      out.write("         fileOut.close();\r\n");
      out.write("         System.out.printf(\"Serialized data is saved in /tmp/items.ser\");\r\n");
      out.write("      }catch(IOException i)\r\n");
      out.write("      {\r\n");
      out.write("          i.printStackTrace();\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("}");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
