/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2016-03-03 18:40:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import servlet.CartController;
import beans.*;

public final class ShoppingCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCT<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Shopping Cart</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("</head>\r\n");
      out.write(" \r\n");
      out.write("<BODY BGCOLOR=\"#FFF5EE\">\r\n");
      out.write("<H1 ALIGN=\"CENTER\">BEST DEAL Inc.</H1>\r\n");
      out.write("<br>\r\n");
      out.write("<H2 ALIGN=\"CENTER\">Shopping Cart</H2>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write("  <p ALIGN=\\\"LEFT\\\">\r\n");
      out.write("\t\t<a href=ModelList.jsp>&nbsp;Home&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a> <a\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=ShoppingCart.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;View\r\n");
      out.write("\t\t\tShopping Cart&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a> \r\n");
      out.write("\t\t<a href=Checkout.html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Checkout</a>\r\n");
      out.write("\t</p>\r\n");
      out.write("\r\n");
      out.write("\t<table width=\"75%\" border=\"1\">\r\n");
      out.write("\t\t<tr bgcolor=\"#CCCCCC\">\r\n");
      out.write("\t\t\t<td><strong><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\">Model Description</font></strong></td>\r\n");
      out.write("\t\t\t<td><strong><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\">Quantity</font></strong></td>\r\n");
      out.write("\t\t\t<td><strong><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\">Unit Price</font></strong></td>\r\n");
      out.write("\t\t\t<td><strong><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\">Total</font></strong></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      beans.CartBean cart = null;
      synchronized (session) {
        cart = (beans.CartBean) _jspx_page_context.getAttribute("cart", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (cart == null){
          cart = new beans.CartBean();
          _jspx_page_context.setAttribute("cart", cart, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\t\t\t\t");
      servlet.CartController servletBean = null;
      servletBean = (servlet.CartController) _jspx_page_context.getAttribute("servletBean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (servletBean == null){
        servletBean = new servlet.CartController();
        _jspx_page_context.setAttribute("servletBean", servletBean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

			
			for (int i = 0; i < cart.getLineItemCount(); i++) {
				String _id = cart.getCartItems().get(i).getItemID();
				String _sDesc = cart.getCartItems().get(i).getShortDescription();
				double _cost = cart.getCartItems().get(i).getCost();
				double _totalcost = cart.getCartItems().get(i).getTotalCost();
				int _quantity = cart.getCartItems().get(i).getQuantity();

		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<form name=\"item\" method=\"POST\" action=\"servlet/CartController\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\"><b>");
      out.print(_sDesc);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</b><br /> \r\n");
      out.write("\t\t\t\t\t    </font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type='hidden' name='itemID' value= \"");
      out.print(_id);
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t\t<input type='hidden' name='itemIndex' value= \"");
      out.print(i);
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t\t<input type='text' name=\"quantity\" value=\"");
      out.print(_quantity );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"Update\"> <br /> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"Delete\">\r\n");
      out.write("\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\">$");
      out.print(_cost );
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\">$");
      out.print(_totalcost);
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\"></td>\r\n");
      out.write("\t\t\t<td></td><td><font size=\"2\" face=\"Verdana, Arial, Helvetica, sans-serif\">Subtotal:");
      out.print(cart.dblOrderTotal );
      out.write("\r\n");
      out.write("\t\t\t</font></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<form align=\"center\" action=\"Checkout.html\" method=\"POST\">\r\n");
      out.write("    <input type=\"submit\" value=\"Proceed to checkout\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
