/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2016-02-21 23:02:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.Date;
import java.util.Enumeration;
import java.util.Calendar;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.util.ArrayList;
import java.util.List;

public final class Tablets_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<!-- \r\n");
      out.write("Final checkout page. :-)\r\n");
      out.write("\r\n");
      out.write("Taken from Core Servlets and JavaServer Pages 2nd Edition\r\n");
      out.write("from Prentice Hall and Sun Microsystems Press,\r\n");
      out.write("http://www.coreservlets.com/.\r\n");
      out.write("(C) 2003 Marty Hall; may be freely used or adapted.\r\n");
      out.write("-->\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("  <TITLE>Tablets</TITLE>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<BODY BGCOLOR=\"#FFF5EE\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<H1 ALIGN=\"CENTER\">BEST DEAL Inc.</H1>\r\n");
      out.write("<br>\r\n");
      out.write("<H2 ALIGN=\"CENTER\">Tablets</H2>\r\n");
      out.write("<br>\r\n");
      out.write("                <p ALIGN=\\\"LEFT\\\">\r\n");
      out.write("\t\t\t\t<a href=Phones.jsp>&nbsp;Phones&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a>\r\n");
      out.write("\t\t\t\t<a href=Tablets.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tablets&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a>\r\n");
      out.write("\t\t\t\t<a href=Laptop.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Laptops&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a>\r\n");
      out.write("\t\t\t\t<a href=TV.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TVs&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a>\r\n");
      out.write("\t\t\t\t<a href=OrderPage.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shopping Cart&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|</a>\r\n");
      out.write("\t\t\t\t<a href=OrderStatus.jsp>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Order Status</a>\r\n");
      out.write("                </p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</BODY></HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
