/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2016-03-14 23:16:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Technicalportal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"customerPortal.js\"></script>\r\n");
      out.write("  <script src=\"technicalsupport.js\"></script>\r\n");
      out.write("<center><img src=\"telecom.png\" alt=\"WideCast Telecom\" width=\"128\" height=\"128\"></center>\r\n");
      out.write("    <title>WideCast Cable</title> \r\n");
      out.write("\t <link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheet.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"topright\">\r\n");
      out.write("<a href=\"Main.jsp\">Home&nbsp;</a>\r\n");
      out.write("<a href=\"About.jsp\">About Us&nbsp;</a>\r\n");
      out.write("<a href=\"Contact.jsp\">Contact Us&nbsp;</a>\r\n");
      out.write("<a href=\"http://www.tvguide.com/\">TV Guide</a>\r\n");
      out.write("</nav>\t\r\n");
      out.write("<H1 ALIGN=\"CENTER\">WideCast Cable</H1>\r\n");
      out.write("<H3 ALIGN=\"CENTER\"><i>We provide Entertainment for more</i></H3>\r\n");
      out.write("<br>\r\n");
      out.write("<H3 ALIGN=\"CENTER\"><i>Incident Management Portal</i></H3>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<a id = \"createIncident\" onclick = 'setNewForm(\"\")'>Create Incident&nbsp;|</a>\r\n");
      out.write("<a id = \"closeIncident\">&nbsp;Close Incident&nbsp;|</a>\r\n");
      out.write("<a href=\"Main.jsp\">&nbsp;Logout</a>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("<div id = \"technicalSupportContainer\">\r\n");
      out.write("  User account look up:\r\n");
      out.write("  <input type=\"text\" name=\"userID\"><br>\r\n");
      out.write("  <br>\r\n");
      out.write("    <input type=\"submit\" value=\"Submit\" id = \"checkID\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\t\r\n");
      out.write("<h3>Real-time call volume per region:</h3>\r\n");
      out.write("<div id=\"graphDiv1\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"graphDiv2\"></div>\r\n");
      out.write("\t<!--[if IE]><script src=\"excanvas.js\"></script><![endif]-->\r\n");
      out.write("\t<script src=\"html5-canvas-bar-graph.js\"></script>\r\n");
      out.write("\t<script>(function () {\r\n");
      out.write("\r\n");
      out.write("\t\tfunction createCanvas(divName) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar div = document.getElementById(divName);\r\n");
      out.write("\t\t\tvar canvas = document.createElement('canvas');\r\n");
      out.write("\t\t\tdiv.appendChild(canvas);\r\n");
      out.write("\t\t\tif (typeof G_vmlCanvasManager != 'undefined') {\r\n");
      out.write("\t\t\t\tcanvas = G_vmlCanvasManager.initElement(canvas);\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\tvar ctx = canvas.getContext(\"2d\");\r\n");
      out.write("\t\t\treturn ctx;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar ctx = createCanvas(\"graphDiv1\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar graph = new BarGraph(ctx);\r\n");
      out.write("\t\tgraph.maxValue = 30;\r\n");
      out.write("\t\tgraph.margin = 2;\r\n");
      out.write("\t\tgraph.colors = [\"#49a0d8\", \"#d353a0\", \"#ffc527\", \"#df4c27\"];\r\n");
      out.write("\t\tgraph.xAxisLabelArr = [\"Northeast\", \"Midwest\", \"West\", \"South\"];\r\n");
      out.write("\t\tsetInterval(function () {\r\n");
      out.write("\t\t\tgraph.update([Math.random() * 6.5, Math.random() * 15.0, Math.random() * 3.5, Math.random() * 20.9]);\r\n");
      out.write("\t\t}, 1000);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t}());</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
