/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2016-02-17 23:19:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp_002dexamples.jsp3.f2;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<HTML>\r\n");
      out.write("<HEAD><TITLE>Java News Today!</TITLE>\r\n");
      out.write("\r\n");
      out.write("<BODY BGCOLOR=\"#FFFFFF\">\r\n");
      out.write("\r\n");
      out.write("<TABLE BORDER=\"0\" WIDTH=\"100%\">\r\n");
      out.write("\r\n");
      out.write("  <TR>\r\n");
      out.write("      <TD BGCOLOR=\"#0000FF\" ALIGN=\"CENTER\" COLSPAN=\"2\">\r\n");
      out.write("      <!-- Begin Header -->\r\n");
      out.write("      <H1>Welcome To Java News Today</H1>\r\n");
      out.write("\r\n");
      out.write("      <P>Your on-line home for up to the minute\r\n");
      out.write("      Java news</P>\r\n");
      out.write("      <!-- End Header -->\r\n");
      out.write("    </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD ALIGN=\"LEFT\" WIDTH=\"20%\" BGCOLOR=\"#000077\">\r\n");
      out.write("      <!-- Begin Navigation -->\r\n");
      out.write("      <FONT COLOR=\"FFFFFF\">\r\n");
      out.write("      <FONT COLOR=\"#FF0000\">&sect;</FONT>\r\n");
      out.write("      Home Page<BR>\r\n");
      out.write("\r\n");
      out.write("      <FONT COLOR=\"#FF0000\">&sect;</FONT>\r\n");
      out.write("      Industry news<BR>\r\n");
      out.write("\r\n");
      out.write("      <FONT COLOR=\"#FF0000\">&sect;</FONT>\r\n");
      out.write("      Enterprise Java<BR>\r\n");
      out.write("\r\n");
      out.write("      <FONT COLOR=\"#FF0000\">&sect;</FONT>\r\n");
      out.write("      Standard Edition Java<BR>\r\n");
      out.write("\r\n");
      out.write("      <FONT COLOR=\"#FF0000\">&sect;</FONT>\r\n");
      out.write("      Micro edition &amp; devices<BR>\r\n");
      out.write("\r\n");
      out.write("      <FONT COLOR=\"#FF0000\">&sect;</FONT>\r\n");
      out.write("      Beans<BR>\r\n");
      out.write("\r\n");
      out.write("      <FONT COLOR=\"#FF0000\">&sect;</FONT>\r\n");
      out.write("      Editorials<BR>\r\n");
      out.write("      </FONT>\r\n");
      out.write("      <!-- End Navigation -->\r\n");
      out.write("    </TD>\r\n");
      out.write("\r\n");
      out.write("    <TD>\r\n");
      out.write("    <!-- Content goes here -->\r\n");
      out.write("    </TD>\r\n");
      out.write("\r\n");
      out.write("  </TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
